version: '3.8'

networks:
  jupyterhub-network:
    name: &networkname jupyterhub-network
    driver: overlay
    attachable: true

services:
  jupyterhub:
    image: xnat/jupyterhub:0.3.0-beta1
    hostname: jupyterhub
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
    ports:
      - "8000:8000"
    networks:
      - jupyterhub-network
    environment:
      JH_NETWORK: *networkname
      JH_UID:
      JH_GID:
      NB_UID:
      NB_GID:
      JH_START_TIMEOUT: 180
      JH_XNAT_URL:
      JH_XNAT_SERVICE_TOKEN:
      JH_XNAT_USERNAME: jupyterhub
      JH_XNAT_PASSWORD:
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
