{{- if .Values.postgres.cluster.enabled }}
{{- if not .Values.postgres.cluster.credentials.externalSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-app-credentials" (include "jupyterhub.postgres.clusterName" .) }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.postgres.cluster.credentials.username }}
  password: {{ .Values.postgres.cluster.credentials.password }}
{{- end }}
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "jupyterhub.postgres.clusterName" . }}
  annotations:
    checksum/cnpg-values: {{ .Values.postgres | toJson | sha256sum }}
spec:
  {{- if .Values.postgres.cluster.affinity }}
  affinity: {{ .Values.postgres.cluster.affinity | toYaml | nindent 4 }}
  {{- end }}
  instances: {{ .Values.postgres.cluster.instances }}
  imageName: ghcr.io/cloudnative-pg/postgresql:{{ .Values.postgres.cluster.version }}
  storage:
    size: {{ .Values.postgres.cluster.storage.size }}
    storageClass: {{ .Values.postgres.cluster.storage.storageClass }}
  resources: {{- .Values.postgres.cluster.resources | toYaml | nindent 4 }}
  enableSuperuserAccess: {{ .Values.postgres.cluster.enableSuperuserAccess }}
  bootstrap:
    initdb:
      database: {{ .Values.postgres.cluster.credentials.database }}
      owner: {{ .Values.postgres.cluster.credentials.username }}
      secret:
        {{- if .Values.postgres.cluster.credentials.externalSecret }}
        name: {{ .Values.postgres.cluster.credentials.externalSecret }}
        {{- else }}
        name: {{ printf "%s-app-credentials" (include "jupyterhub.postgres.clusterName" .) }}
        {{- end }}
  postgresql:
    parameters: {{- .Values.postgres.cluster.parameters | toYaml | nindent 6 }}
  {{- if .Values.postgres.cluster.managed }}
  managed: {{- .Values.postgres.cluster.managed | toYaml | nindent 4 }}
  {{- end }}
{{- end }}
