{{- if (not .Values.postgres.cluster.enabled) and (eq (lower .Values.jupyterhub.hub.db.type) "postgres") }}
{{- if .Values.postgres.external.postgresUri }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "jupyterhub.postgres.fullname" . }}
spec:
  type: ExternalName
  externalName: {{ .Values.postgres.external.postgresUri }}
{{- else if .Values.postgres.external.postgresIp }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "jupyterhub.postgres.fullname" . }}
spec:
  type: ClusterIP
  ports:
    - port: {{ include "jupyterhub.postgres.postgresPort" . }}
      targetPort: {{ include "jupyterhub.postgres.postgresPort" . }}
      protocol: TCP
      name: postgres
---
apiVersion: v1
kind: EndpointSlice
metadata:
  name: {{ include "jupyterhub.postgres.fullname" . }}
  labels:
    kubernetes.io/service-name: {{ include "jupyterhub.postgres.fullname" . }}
addressType: IPv4
endpoints:
  - addresses:
      - "{{ .Values.postgres.external.postgresIp }}"
ports:
  - port: {{ include "jupyterhub.postgres.postgresPort" . }}
    protocol: TCP
{{- end }}
{{- end }}
