apiVersion: v2
name: jupyterhub-xnat
description: Helm xnat-jupyterhub-chart for deploying JupyterHub (and PostgreSQL) for an XNAT instance
type: application
version: 0.1.0
appVersion: "1.1.0"

dependencies:
- name: postgresql
  version: "10.16.2"  # posgresql app version 11.14.0
  repository: "https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami"
  condition: postgresql.enabled
- name: jupyterhub
  version: "3.0.0" # jupyterhub app version 4.0.0
  repository: "https://hub.jupyter.org/helm-chart/"
  condition: jupyterhub.enabled